// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: refund/v1/core.proto

package refundv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPaymentGatewayCredentialRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PaymentGatewayCode string                 `protobuf:"bytes,1,opt,name=payment_gateway_code,json=paymentGatewayCode,proto3" json:"payment_gateway_code,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetPaymentGatewayCredentialRequest) Reset() {
	*x = GetPaymentGatewayCredentialRequest{}
	mi := &file_refund_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentGatewayCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentGatewayCredentialRequest) ProtoMessage() {}

func (x *GetPaymentGatewayCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_refund_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentGatewayCredentialRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentGatewayCredentialRequest) Descriptor() ([]byte, []int) {
	return file_refund_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *GetPaymentGatewayCredentialRequest) GetPaymentGatewayCode() string {
	if x != nil {
		return x.PaymentGatewayCode
	}
	return ""
}

type GetPaymentGatewayCredentialResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The decrypted provider credential envelope. Its JSON shape is provider
	// specific and preserves the existing development/production object.
	CredentialJson string `protobuf:"bytes,1,opt,name=credential_json,json=credentialJson,proto3" json:"credential_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPaymentGatewayCredentialResponse) Reset() {
	*x = GetPaymentGatewayCredentialResponse{}
	mi := &file_refund_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentGatewayCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentGatewayCredentialResponse) ProtoMessage() {}

func (x *GetPaymentGatewayCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_refund_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentGatewayCredentialResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentGatewayCredentialResponse) Descriptor() ([]byte, []int) {
	return file_refund_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *GetPaymentGatewayCredentialResponse) GetCredentialJson() string {
	if x != nil {
		return x.CredentialJson
	}
	return ""
}

var File_refund_v1_core_proto protoreflect.FileDescriptor

const file_refund_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x14refund/v1/core.proto\x12\x13bridgepay.refund.v1\"V\n" +
	"\"GetPaymentGatewayCredentialRequest\x120\n" +
	"\x14payment_gateway_code\x18\x01 \x01(\tR\x12paymentGatewayCode\"N\n" +
	"#GetPaymentGatewayCredentialResponse\x12'\n" +
	"\x0fcredential_json\x18\x01 \x01(\tR\x0ecredentialJson2\xa6\x01\n" +
	"\x11RefundCoreService\x12\x90\x01\n" +
	"\x1bGetPaymentGatewayCredential\x127.bridgepay.refund.v1.GetPaymentGatewayCredentialRequest\x1a8.bridgepay.refund.v1.GetPaymentGatewayCredentialResponseB0Z.bridgepay-payment-contracts/refund/v1;refundv1b\x06proto3"

var (
	file_refund_v1_core_proto_rawDescOnce sync.Once
	file_refund_v1_core_proto_rawDescData []byte
)

func file_refund_v1_core_proto_rawDescGZIP() []byte {
	file_refund_v1_core_proto_rawDescOnce.Do(func() {
		file_refund_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_refund_v1_core_proto_rawDesc), len(file_refund_v1_core_proto_rawDesc)))
	})
	return file_refund_v1_core_proto_rawDescData
}

var file_refund_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_refund_v1_core_proto_goTypes = []any{
	(*GetPaymentGatewayCredentialRequest)(nil),  // 0: bridgepay.refund.v1.GetPaymentGatewayCredentialRequest
	(*GetPaymentGatewayCredentialResponse)(nil), // 1: bridgepay.refund.v1.GetPaymentGatewayCredentialResponse
}
var file_refund_v1_core_proto_depIdxs = []int32{
	0, // 0: bridgepay.refund.v1.RefundCoreService.GetPaymentGatewayCredential:input_type -> bridgepay.refund.v1.GetPaymentGatewayCredentialRequest
	1, // 1: bridgepay.refund.v1.RefundCoreService.GetPaymentGatewayCredential:output_type -> bridgepay.refund.v1.GetPaymentGatewayCredentialResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_refund_v1_core_proto_init() }
func file_refund_v1_core_proto_init() {
	if File_refund_v1_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_refund_v1_core_proto_rawDesc), len(file_refund_v1_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_refund_v1_core_proto_goTypes,
		DependencyIndexes: file_refund_v1_core_proto_depIdxs,
		MessageInfos:      file_refund_v1_core_proto_msgTypes,
	}.Build()
	File_refund_v1_core_proto = out.File
	file_refund_v1_core_proto_goTypes = nil
	file_refund_v1_core_proto_depIdxs = nil
}
