// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: refund/v1/core.proto

package refundv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RefundCoreService_GetPaymentGatewayCredential_FullMethodName = "/bridgepay.refund.v1.RefundCoreService/GetPaymentGatewayCredential"
)

// RefundCoreServiceClient is the client API for RefundCoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RefundCoreService is the synchronous, Go-only Refund-to-Core boundary.
// Core owns payment-gateway credentials; Refund receives only the credential
// requested for its provider and never reads Core's tables directly.
type RefundCoreServiceClient interface {
	GetPaymentGatewayCredential(ctx context.Context, in *GetPaymentGatewayCredentialRequest, opts ...grpc.CallOption) (*GetPaymentGatewayCredentialResponse, error)
}

type refundCoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRefundCoreServiceClient(cc grpc.ClientConnInterface) RefundCoreServiceClient {
	return &refundCoreServiceClient{cc}
}

func (c *refundCoreServiceClient) GetPaymentGatewayCredential(ctx context.Context, in *GetPaymentGatewayCredentialRequest, opts ...grpc.CallOption) (*GetPaymentGatewayCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentGatewayCredentialResponse)
	err := c.cc.Invoke(ctx, RefundCoreService_GetPaymentGatewayCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RefundCoreServiceServer is the server API for RefundCoreService service.
// All implementations must embed UnimplementedRefundCoreServiceServer
// for forward compatibility.
//
// RefundCoreService is the synchronous, Go-only Refund-to-Core boundary.
// Core owns payment-gateway credentials; Refund receives only the credential
// requested for its provider and never reads Core's tables directly.
type RefundCoreServiceServer interface {
	GetPaymentGatewayCredential(context.Context, *GetPaymentGatewayCredentialRequest) (*GetPaymentGatewayCredentialResponse, error)
	mustEmbedUnimplementedRefundCoreServiceServer()
}

// UnimplementedRefundCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRefundCoreServiceServer struct{}

func (UnimplementedRefundCoreServiceServer) GetPaymentGatewayCredential(context.Context, *GetPaymentGatewayCredentialRequest) (*GetPaymentGatewayCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentGatewayCredential not implemented")
}
func (UnimplementedRefundCoreServiceServer) mustEmbedUnimplementedRefundCoreServiceServer() {}
func (UnimplementedRefundCoreServiceServer) testEmbeddedByValue()                           {}

// UnsafeRefundCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RefundCoreServiceServer will
// result in compilation errors.
type UnsafeRefundCoreServiceServer interface {
	mustEmbedUnimplementedRefundCoreServiceServer()
}

func RegisterRefundCoreServiceServer(s grpc.ServiceRegistrar, srv RefundCoreServiceServer) {
	// If the following call panics, it indicates UnimplementedRefundCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RefundCoreService_ServiceDesc, srv)
}

func _RefundCoreService_GetPaymentGatewayCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentGatewayCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundCoreServiceServer).GetPaymentGatewayCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RefundCoreService_GetPaymentGatewayCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundCoreServiceServer).GetPaymentGatewayCredential(ctx, req.(*GetPaymentGatewayCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RefundCoreService_ServiceDesc is the grpc.ServiceDesc for RefundCoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RefundCoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridgepay.refund.v1.RefundCoreService",
	HandlerType: (*RefundCoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPaymentGatewayCredential",
			Handler:    _RefundCoreService_GetPaymentGatewayCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "refund/v1/core.proto",
}
