// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: refund/v1/gateway.proto

package refundv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RefundGatewayService_ListBanks_FullMethodName            = "/bridgepay.refund.v1.RefundGatewayService/ListBanks"
	RefundGatewayService_CheckAccount_FullMethodName         = "/bridgepay.refund.v1.RefundGatewayService/CheckAccount"
	RefundGatewayService_AcceptIlumaCallback_FullMethodName  = "/bridgepay.refund.v1.RefundGatewayService/AcceptIlumaCallback"
	RefundGatewayService_CreateRefund_FullMethodName         = "/bridgepay.refund.v1.RefundGatewayService/CreateRefund"
	RefundGatewayService_GetRefundStatus_FullMethodName      = "/bridgepay.refund.v1.RefundGatewayService/GetRefundStatus"
	RefundGatewayService_AcceptXenditCallback_FullMethodName = "/bridgepay.refund.v1.RefundGatewayService/AcceptXenditCallback"
)

// RefundGatewayServiceClient is the client API for RefundGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RefundGatewayService is the synchronous Gateway-Go to Refund-Go boundary.
// Durable background work remains on RabbitMQ.
type RefundGatewayServiceClient interface {
	ListBanks(ctx context.Context, in *ListBanksRequest, opts ...grpc.CallOption) (*RefundHTTPResponse, error)
	CheckAccount(ctx context.Context, in *CheckAccountRequest, opts ...grpc.CallOption) (*RefundHTTPResponse, error)
	AcceptIlumaCallback(ctx context.Context, in *AcceptIlumaCallbackRequest, opts ...grpc.CallOption) (*RefundHTTPResponse, error)
	CreateRefund(ctx context.Context, in *CreateRefundRequest, opts ...grpc.CallOption) (*RefundHTTPResponse, error)
	GetRefundStatus(ctx context.Context, in *GetRefundStatusRequest, opts ...grpc.CallOption) (*RefundHTTPResponse, error)
	AcceptXenditCallback(ctx context.Context, in *AcceptXenditCallbackRequest, opts ...grpc.CallOption) (*RefundHTTPResponse, error)
}

type refundGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRefundGatewayServiceClient(cc grpc.ClientConnInterface) RefundGatewayServiceClient {
	return &refundGatewayServiceClient{cc}
}

func (c *refundGatewayServiceClient) ListBanks(ctx context.Context, in *ListBanksRequest, opts ...grpc.CallOption) (*RefundHTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundHTTPResponse)
	err := c.cc.Invoke(ctx, RefundGatewayService_ListBanks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refundGatewayServiceClient) CheckAccount(ctx context.Context, in *CheckAccountRequest, opts ...grpc.CallOption) (*RefundHTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundHTTPResponse)
	err := c.cc.Invoke(ctx, RefundGatewayService_CheckAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refundGatewayServiceClient) AcceptIlumaCallback(ctx context.Context, in *AcceptIlumaCallbackRequest, opts ...grpc.CallOption) (*RefundHTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundHTTPResponse)
	err := c.cc.Invoke(ctx, RefundGatewayService_AcceptIlumaCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refundGatewayServiceClient) CreateRefund(ctx context.Context, in *CreateRefundRequest, opts ...grpc.CallOption) (*RefundHTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundHTTPResponse)
	err := c.cc.Invoke(ctx, RefundGatewayService_CreateRefund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refundGatewayServiceClient) GetRefundStatus(ctx context.Context, in *GetRefundStatusRequest, opts ...grpc.CallOption) (*RefundHTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundHTTPResponse)
	err := c.cc.Invoke(ctx, RefundGatewayService_GetRefundStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refundGatewayServiceClient) AcceptXenditCallback(ctx context.Context, in *AcceptXenditCallbackRequest, opts ...grpc.CallOption) (*RefundHTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundHTTPResponse)
	err := c.cc.Invoke(ctx, RefundGatewayService_AcceptXenditCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RefundGatewayServiceServer is the server API for RefundGatewayService service.
// All implementations must embed UnimplementedRefundGatewayServiceServer
// for forward compatibility.
//
// RefundGatewayService is the synchronous Gateway-Go to Refund-Go boundary.
// Durable background work remains on RabbitMQ.
type RefundGatewayServiceServer interface {
	ListBanks(context.Context, *ListBanksRequest) (*RefundHTTPResponse, error)
	CheckAccount(context.Context, *CheckAccountRequest) (*RefundHTTPResponse, error)
	AcceptIlumaCallback(context.Context, *AcceptIlumaCallbackRequest) (*RefundHTTPResponse, error)
	CreateRefund(context.Context, *CreateRefundRequest) (*RefundHTTPResponse, error)
	GetRefundStatus(context.Context, *GetRefundStatusRequest) (*RefundHTTPResponse, error)
	AcceptXenditCallback(context.Context, *AcceptXenditCallbackRequest) (*RefundHTTPResponse, error)
	mustEmbedUnimplementedRefundGatewayServiceServer()
}

// UnimplementedRefundGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRefundGatewayServiceServer struct{}

func (UnimplementedRefundGatewayServiceServer) ListBanks(context.Context, *ListBanksRequest) (*RefundHTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBanks not implemented")
}
func (UnimplementedRefundGatewayServiceServer) CheckAccount(context.Context, *CheckAccountRequest) (*RefundHTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAccount not implemented")
}
func (UnimplementedRefundGatewayServiceServer) AcceptIlumaCallback(context.Context, *AcceptIlumaCallbackRequest) (*RefundHTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptIlumaCallback not implemented")
}
func (UnimplementedRefundGatewayServiceServer) CreateRefund(context.Context, *CreateRefundRequest) (*RefundHTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRefund not implemented")
}
func (UnimplementedRefundGatewayServiceServer) GetRefundStatus(context.Context, *GetRefundStatusRequest) (*RefundHTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRefundStatus not implemented")
}
func (UnimplementedRefundGatewayServiceServer) AcceptXenditCallback(context.Context, *AcceptXenditCallbackRequest) (*RefundHTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptXenditCallback not implemented")
}
func (UnimplementedRefundGatewayServiceServer) mustEmbedUnimplementedRefundGatewayServiceServer() {}
func (UnimplementedRefundGatewayServiceServer) testEmbeddedByValue()                              {}

// UnsafeRefundGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RefundGatewayServiceServer will
// result in compilation errors.
type UnsafeRefundGatewayServiceServer interface {
	mustEmbedUnimplementedRefundGatewayServiceServer()
}

func RegisterRefundGatewayServiceServer(s grpc.ServiceRegistrar, srv RefundGatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedRefundGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RefundGatewayService_ServiceDesc, srv)
}

func _RefundGatewayService_ListBanks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBanksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundGatewayServiceServer).ListBanks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RefundGatewayService_ListBanks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundGatewayServiceServer).ListBanks(ctx, req.(*ListBanksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RefundGatewayService_CheckAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundGatewayServiceServer).CheckAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RefundGatewayService_CheckAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundGatewayServiceServer).CheckAccount(ctx, req.(*CheckAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RefundGatewayService_AcceptIlumaCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptIlumaCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundGatewayServiceServer).AcceptIlumaCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RefundGatewayService_AcceptIlumaCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundGatewayServiceServer).AcceptIlumaCallback(ctx, req.(*AcceptIlumaCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RefundGatewayService_CreateRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundGatewayServiceServer).CreateRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RefundGatewayService_CreateRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundGatewayServiceServer).CreateRefund(ctx, req.(*CreateRefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RefundGatewayService_GetRefundStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRefundStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundGatewayServiceServer).GetRefundStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RefundGatewayService_GetRefundStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundGatewayServiceServer).GetRefundStatus(ctx, req.(*GetRefundStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RefundGatewayService_AcceptXenditCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptXenditCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundGatewayServiceServer).AcceptXenditCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RefundGatewayService_AcceptXenditCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundGatewayServiceServer).AcceptXenditCallback(ctx, req.(*AcceptXenditCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RefundGatewayService_ServiceDesc is the grpc.ServiceDesc for RefundGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RefundGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridgepay.refund.v1.RefundGatewayService",
	HandlerType: (*RefundGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBanks",
			Handler:    _RefundGatewayService_ListBanks_Handler,
		},
		{
			MethodName: "CheckAccount",
			Handler:    _RefundGatewayService_CheckAccount_Handler,
		},
		{
			MethodName: "AcceptIlumaCallback",
			Handler:    _RefundGatewayService_AcceptIlumaCallback_Handler,
		},
		{
			MethodName: "CreateRefund",
			Handler:    _RefundGatewayService_CreateRefund_Handler,
		},
		{
			MethodName: "GetRefundStatus",
			Handler:    _RefundGatewayService_GetRefundStatus_Handler,
		},
		{
			MethodName: "AcceptXenditCallback",
			Handler:    _RefundGatewayService_AcceptXenditCallback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "refund/v1/gateway.proto",
}
