// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: refund/v1/gateway.proto

package refundv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefundRequestContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RefundRequestContext) Reset() {
	*x = RefundRequestContext{}
	mi := &file_refund_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequestContext) ProtoMessage() {}

func (x *RefundRequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_refund_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequestContext.ProtoReflect.Descriptor instead.
func (*RefundRequestContext) Descriptor() ([]byte, []int) {
	return file_refund_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *RefundRequestContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RefundRequestContext) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type RefundAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BankId        string                 `protobuf:"bytes,1,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	AccountNo     string                 `protobuf:"bytes,2,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	AccountType   string                 `protobuf:"bytes,3,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	IdNo          string                 `protobuf:"bytes,4,opt,name=id_no,json=idNo,proto3" json:"id_no,omitempty"`
	IdType        string                 `protobuf:"bytes,5,opt,name=id_type,json=idType,proto3" json:"id_type,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundAccount) Reset() {
	*x = RefundAccount{}
	mi := &file_refund_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundAccount) ProtoMessage() {}

func (x *RefundAccount) ProtoReflect() protoreflect.Message {
	mi := &file_refund_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundAccount.ProtoReflect.Descriptor instead.
func (*RefundAccount) Descriptor() ([]byte, []int) {
	return file_refund_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *RefundAccount) GetBankId() string {
	if x != nil {
		return x.BankId
	}
	return ""
}

func (x *RefundAccount) GetAccountNo() string {
	if x != nil {
		return x.AccountNo
	}
	return ""
}

func (x *RefundAccount) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *RefundAccount) GetIdNo() string {
	if x != nil {
		return x.IdNo
	}
	return ""
}

func (x *RefundAccount) GetIdType() string {
	if x != nil {
		return x.IdType
	}
	return ""
}

func (x *RefundAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListBanksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RefundRequestContext  `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBanksRequest) Reset() {
	*x = ListBanksRequest{}
	mi := &file_refund_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBanksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBanksRequest) ProtoMessage() {}

func (x *ListBanksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_refund_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBanksRequest.ProtoReflect.Descriptor instead.
func (*ListBanksRequest) Descriptor() ([]byte, []int) {
	return file_refund_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ListBanksRequest) GetContext() *RefundRequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type CheckAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RefundRequestContext  `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Account       *RefundAccount         `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	SignMsg       string                 `protobuf:"bytes,3,opt,name=sign_msg,json=signMsg,proto3" json:"sign_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccountRequest) Reset() {
	*x = CheckAccountRequest{}
	mi := &file_refund_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccountRequest) ProtoMessage() {}

func (x *CheckAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_refund_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccountRequest.ProtoReflect.Descriptor instead.
func (*CheckAccountRequest) Descriptor() ([]byte, []int) {
	return file_refund_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *CheckAccountRequest) GetContext() *RefundRequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CheckAccountRequest) GetAccount() *RefundAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *CheckAccountRequest) GetSignMsg() string {
	if x != nil {
		return x.SignMsg
	}
	return ""
}

type RefundInvoice struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OrderId             string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	RefundAmount        *int64                 `protobuf:"varint,2,opt,name=refund_amount,json=refundAmount,proto3,oneof" json:"refund_amount,omitempty"`
	Reason              string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Passengers          string                 `protobuf:"bytes,4,opt,name=passengers,proto3" json:"passengers,omitempty"`
	OriginalOrderNumber string                 `protobuf:"bytes,5,opt,name=original_order_number,json=originalOrderNumber,proto3" json:"original_order_number,omitempty"`
	NotifyUrl           string                 `protobuf:"bytes,6,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	TicketOffice        string                 `protobuf:"bytes,7,opt,name=ticket_office,json=ticketOffice,proto3" json:"ticket_office,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RefundInvoice) Reset() {
	*x = RefundInvoice{}
	mi := &file_refund_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundInvoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundInvoice) ProtoMessage() {}

func (x *RefundInvoice) ProtoReflect() protoreflect.Message {
	mi := &file_refund_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundInvoice.ProtoReflect.Descriptor instead.
func (*RefundInvoice) Descriptor() ([]byte, []int) {
	return file_refund_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *RefundInvoice) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RefundInvoice) GetRefundAmount() int64 {
	if x != nil && x.RefundAmount != nil {
		return *x.RefundAmount
	}
	return 0
}

func (x *RefundInvoice) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RefundInvoice) GetPassengers() string {
	if x != nil {
		return x.Passengers
	}
	return ""
}

func (x *RefundInvoice) GetOriginalOrderNumber() string {
	if x != nil {
		return x.OriginalOrderNumber
	}
	return ""
}

func (x *RefundInvoice) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *RefundInvoice) GetTicketOffice() string {
	if x != nil {
		return x.TicketOffice
	}
	return ""
}

type CreateRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RefundRequestContext  `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Account       *RefundAccount         `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Invoice       *RefundInvoice         `protobuf:"bytes,3,opt,name=invoice,proto3" json:"invoice,omitempty"`
	SignMsg       string                 `protobuf:"bytes,4,opt,name=sign_msg,json=signMsg,proto3" json:"sign_msg,omitempty"`
	TicketCall    *int64                 `protobuf:"varint,5,opt,name=ticket_call,json=ticketCall,proto3,oneof" json:"ticket_call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRefundRequest) Reset() {
	*x = CreateRefundRequest{}
	mi := &file_refund_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRefundRequest) ProtoMessage() {}

func (x *CreateRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_refund_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRefundRequest.ProtoReflect.Descriptor instead.
func (*CreateRefundRequest) Descriptor() ([]byte, []int) {
	return file_refund_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRefundRequest) GetContext() *RefundRequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreateRefundRequest) GetAccount() *RefundAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *CreateRefundRequest) GetInvoice() *RefundInvoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

func (x *CreateRefundRequest) GetSignMsg() string {
	if x != nil {
		return x.SignMsg
	}
	return ""
}

func (x *CreateRefundRequest) GetTicketCall() int64 {
	if x != nil && x.TicketCall != nil {
		return *x.TicketCall
	}
	return 0
}

type GetRefundStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RefundRequestContext  `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SignMsg       string                 `protobuf:"bytes,3,opt,name=sign_msg,json=signMsg,proto3" json:"sign_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRefundStatusRequest) Reset() {
	*x = GetRefundStatusRequest{}
	mi := &file_refund_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRefundStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefundStatusRequest) ProtoMessage() {}

func (x *GetRefundStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_refund_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefundStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRefundStatusRequest) Descriptor() ([]byte, []int) {
	return file_refund_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *GetRefundStatusRequest) GetContext() *RefundRequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetRefundStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetRefundStatusRequest) GetSignMsg() string {
	if x != nil {
		return x.SignMsg
	}
	return ""
}

type AcceptIlumaCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RefundRequestContext  `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptIlumaCallbackRequest) Reset() {
	*x = AcceptIlumaCallbackRequest{}
	mi := &file_refund_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptIlumaCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptIlumaCallbackRequest) ProtoMessage() {}

func (x *AcceptIlumaCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_refund_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptIlumaCallbackRequest.ProtoReflect.Descriptor instead.
func (*AcceptIlumaCallbackRequest) Descriptor() ([]byte, []int) {
	return file_refund_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *AcceptIlumaCallbackRequest) GetContext() *RefundRequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *AcceptIlumaCallbackRequest) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

type AcceptXenditCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RefundRequestContext  `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	CallbackToken string                 `protobuf:"bytes,3,opt,name=callback_token,json=callbackToken,proto3" json:"callback_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptXenditCallbackRequest) Reset() {
	*x = AcceptXenditCallbackRequest{}
	mi := &file_refund_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptXenditCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptXenditCallbackRequest) ProtoMessage() {}

func (x *AcceptXenditCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_refund_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptXenditCallbackRequest.ProtoReflect.Descriptor instead.
func (*AcceptXenditCallbackRequest) Descriptor() ([]byte, []int) {
	return file_refund_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptXenditCallbackRequest) GetContext() *RefundRequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *AcceptXenditCallbackRequest) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *AcceptXenditCallbackRequest) GetCallbackToken() string {
	if x != nil {
		return x.CallbackToken
	}
	return ""
}

// body_json is produced by Refund-Go and returned verbatim by Gateway-Go.
// This preserves the signed public HTTP contract without moving signing or
// business wording into Gateway.
type RefundHTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BodyJson      []byte                 `protobuf:"bytes,1,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundHTTPResponse) Reset() {
	*x = RefundHTTPResponse{}
	mi := &file_refund_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundHTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundHTTPResponse) ProtoMessage() {}

func (x *RefundHTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_refund_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundHTTPResponse.ProtoReflect.Descriptor instead.
func (*RefundHTTPResponse) Descriptor() ([]byte, []int) {
	return file_refund_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *RefundHTTPResponse) GetBodyJson() []byte {
	if x != nil {
		return x.BodyJson
	}
	return nil
}

var File_refund_v1_gateway_proto protoreflect.FileDescriptor

const file_refund_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x17refund/v1/gateway.proto\x12\x13bridgepay.refund.v1\"^\n" +
	"\x14RefundRequestContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"\xac\x01\n" +
	"\rRefundAccount\x12\x17\n" +
	"\abank_id\x18\x01 \x01(\tR\x06bankId\x12\x1d\n" +
	"\n" +
	"account_no\x18\x02 \x01(\tR\taccountNo\x12!\n" +
	"\faccount_type\x18\x03 \x01(\tR\vaccountType\x12\x13\n" +
	"\x05id_no\x18\x04 \x01(\tR\x04idNo\x12\x17\n" +
	"\aid_type\x18\x05 \x01(\tR\x06idType\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\"W\n" +
	"\x10ListBanksRequest\x12C\n" +
	"\acontext\x18\x01 \x01(\v2).bridgepay.refund.v1.RefundRequestContextR\acontext\"\xb3\x01\n" +
	"\x13CheckAccountRequest\x12C\n" +
	"\acontext\x18\x01 \x01(\v2).bridgepay.refund.v1.RefundRequestContextR\acontext\x12<\n" +
	"\aaccount\x18\x02 \x01(\v2\".bridgepay.refund.v1.RefundAccountR\aaccount\x12\x19\n" +
	"\bsign_msg\x18\x03 \x01(\tR\asignMsg\"\x96\x02\n" +
	"\rRefundInvoice\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12(\n" +
	"\rrefund_amount\x18\x02 \x01(\x03H\x00R\frefundAmount\x88\x01\x01\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1e\n" +
	"\n" +
	"passengers\x18\x04 \x01(\tR\n" +
	"passengers\x122\n" +
	"\x15original_order_number\x18\x05 \x01(\tR\x13originalOrderNumber\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x06 \x01(\tR\tnotifyUrl\x12#\n" +
	"\rticket_office\x18\a \x01(\tR\fticketOfficeB\x10\n" +
	"\x0e_refund_amount\"\xa7\x02\n" +
	"\x13CreateRefundRequest\x12C\n" +
	"\acontext\x18\x01 \x01(\v2).bridgepay.refund.v1.RefundRequestContextR\acontext\x12<\n" +
	"\aaccount\x18\x02 \x01(\v2\".bridgepay.refund.v1.RefundAccountR\aaccount\x12<\n" +
	"\ainvoice\x18\x03 \x01(\v2\".bridgepay.refund.v1.RefundInvoiceR\ainvoice\x12\x19\n" +
	"\bsign_msg\x18\x04 \x01(\tR\asignMsg\x12$\n" +
	"\vticket_call\x18\x05 \x01(\x03H\x00R\n" +
	"ticketCall\x88\x01\x01B\x0e\n" +
	"\f_ticket_call\"\x93\x01\n" +
	"\x16GetRefundStatusRequest\x12C\n" +
	"\acontext\x18\x01 \x01(\v2).bridgepay.refund.v1.RefundRequestContextR\acontext\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x19\n" +
	"\bsign_msg\x18\x03 \x01(\tR\asignMsg\"\x84\x01\n" +
	"\x1aAcceptIlumaCallbackRequest\x12C\n" +
	"\acontext\x18\x01 \x01(\v2).bridgepay.refund.v1.RefundRequestContextR\acontext\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\fR\vpayloadJson\"\xac\x01\n" +
	"\x1bAcceptXenditCallbackRequest\x12C\n" +
	"\acontext\x18\x01 \x01(\v2).bridgepay.refund.v1.RefundRequestContextR\acontext\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\fR\vpayloadJson\x12%\n" +
	"\x0ecallback_token\x18\x03 \x01(\tR\rcallbackToken\"1\n" +
	"\x12RefundHTTPResponse\x12\x1b\n" +
	"\tbody_json\x18\x01 \x01(\fR\bbodyJson2\x86\x05\n" +
	"\x14RefundGatewayService\x12[\n" +
	"\tListBanks\x12%.bridgepay.refund.v1.ListBanksRequest\x1a'.bridgepay.refund.v1.RefundHTTPResponse\x12a\n" +
	"\fCheckAccount\x12(.bridgepay.refund.v1.CheckAccountRequest\x1a'.bridgepay.refund.v1.RefundHTTPResponse\x12o\n" +
	"\x13AcceptIlumaCallback\x12/.bridgepay.refund.v1.AcceptIlumaCallbackRequest\x1a'.bridgepay.refund.v1.RefundHTTPResponse\x12a\n" +
	"\fCreateRefund\x12(.bridgepay.refund.v1.CreateRefundRequest\x1a'.bridgepay.refund.v1.RefundHTTPResponse\x12g\n" +
	"\x0fGetRefundStatus\x12+.bridgepay.refund.v1.GetRefundStatusRequest\x1a'.bridgepay.refund.v1.RefundHTTPResponse\x12q\n" +
	"\x14AcceptXenditCallback\x120.bridgepay.refund.v1.AcceptXenditCallbackRequest\x1a'.bridgepay.refund.v1.RefundHTTPResponseB0Z.bridgepay-payment-contracts/refund/v1;refundv1b\x06proto3"

var (
	file_refund_v1_gateway_proto_rawDescOnce sync.Once
	file_refund_v1_gateway_proto_rawDescData []byte
)

func file_refund_v1_gateway_proto_rawDescGZIP() []byte {
	file_refund_v1_gateway_proto_rawDescOnce.Do(func() {
		file_refund_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_refund_v1_gateway_proto_rawDesc), len(file_refund_v1_gateway_proto_rawDesc)))
	})
	return file_refund_v1_gateway_proto_rawDescData
}

var file_refund_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_refund_v1_gateway_proto_goTypes = []any{
	(*RefundRequestContext)(nil),        // 0: bridgepay.refund.v1.RefundRequestContext
	(*RefundAccount)(nil),               // 1: bridgepay.refund.v1.RefundAccount
	(*ListBanksRequest)(nil),            // 2: bridgepay.refund.v1.ListBanksRequest
	(*CheckAccountRequest)(nil),         // 3: bridgepay.refund.v1.CheckAccountRequest
	(*RefundInvoice)(nil),               // 4: bridgepay.refund.v1.RefundInvoice
	(*CreateRefundRequest)(nil),         // 5: bridgepay.refund.v1.CreateRefundRequest
	(*GetRefundStatusRequest)(nil),      // 6: bridgepay.refund.v1.GetRefundStatusRequest
	(*AcceptIlumaCallbackRequest)(nil),  // 7: bridgepay.refund.v1.AcceptIlumaCallbackRequest
	(*AcceptXenditCallbackRequest)(nil), // 8: bridgepay.refund.v1.AcceptXenditCallbackRequest
	(*RefundHTTPResponse)(nil),          // 9: bridgepay.refund.v1.RefundHTTPResponse
}
var file_refund_v1_gateway_proto_depIdxs = []int32{
	0,  // 0: bridgepay.refund.v1.ListBanksRequest.context:type_name -> bridgepay.refund.v1.RefundRequestContext
	0,  // 1: bridgepay.refund.v1.CheckAccountRequest.context:type_name -> bridgepay.refund.v1.RefundRequestContext
	1,  // 2: bridgepay.refund.v1.CheckAccountRequest.account:type_name -> bridgepay.refund.v1.RefundAccount
	0,  // 3: bridgepay.refund.v1.CreateRefundRequest.context:type_name -> bridgepay.refund.v1.RefundRequestContext
	1,  // 4: bridgepay.refund.v1.CreateRefundRequest.account:type_name -> bridgepay.refund.v1.RefundAccount
	4,  // 5: bridgepay.refund.v1.CreateRefundRequest.invoice:type_name -> bridgepay.refund.v1.RefundInvoice
	0,  // 6: bridgepay.refund.v1.GetRefundStatusRequest.context:type_name -> bridgepay.refund.v1.RefundRequestContext
	0,  // 7: bridgepay.refund.v1.AcceptIlumaCallbackRequest.context:type_name -> bridgepay.refund.v1.RefundRequestContext
	0,  // 8: bridgepay.refund.v1.AcceptXenditCallbackRequest.context:type_name -> bridgepay.refund.v1.RefundRequestContext
	2,  // 9: bridgepay.refund.v1.RefundGatewayService.ListBanks:input_type -> bridgepay.refund.v1.ListBanksRequest
	3,  // 10: bridgepay.refund.v1.RefundGatewayService.CheckAccount:input_type -> bridgepay.refund.v1.CheckAccountRequest
	7,  // 11: bridgepay.refund.v1.RefundGatewayService.AcceptIlumaCallback:input_type -> bridgepay.refund.v1.AcceptIlumaCallbackRequest
	5,  // 12: bridgepay.refund.v1.RefundGatewayService.CreateRefund:input_type -> bridgepay.refund.v1.CreateRefundRequest
	6,  // 13: bridgepay.refund.v1.RefundGatewayService.GetRefundStatus:input_type -> bridgepay.refund.v1.GetRefundStatusRequest
	8,  // 14: bridgepay.refund.v1.RefundGatewayService.AcceptXenditCallback:input_type -> bridgepay.refund.v1.AcceptXenditCallbackRequest
	9,  // 15: bridgepay.refund.v1.RefundGatewayService.ListBanks:output_type -> bridgepay.refund.v1.RefundHTTPResponse
	9,  // 16: bridgepay.refund.v1.RefundGatewayService.CheckAccount:output_type -> bridgepay.refund.v1.RefundHTTPResponse
	9,  // 17: bridgepay.refund.v1.RefundGatewayService.AcceptIlumaCallback:output_type -> bridgepay.refund.v1.RefundHTTPResponse
	9,  // 18: bridgepay.refund.v1.RefundGatewayService.CreateRefund:output_type -> bridgepay.refund.v1.RefundHTTPResponse
	9,  // 19: bridgepay.refund.v1.RefundGatewayService.GetRefundStatus:output_type -> bridgepay.refund.v1.RefundHTTPResponse
	9,  // 20: bridgepay.refund.v1.RefundGatewayService.AcceptXenditCallback:output_type -> bridgepay.refund.v1.RefundHTTPResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_refund_v1_gateway_proto_init() }
func file_refund_v1_gateway_proto_init() {
	if File_refund_v1_gateway_proto != nil {
		return
	}
	file_refund_v1_gateway_proto_msgTypes[4].OneofWrappers = []any{}
	file_refund_v1_gateway_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_refund_v1_gateway_proto_rawDesc), len(file_refund_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_refund_v1_gateway_proto_goTypes,
		DependencyIndexes: file_refund_v1_gateway_proto_depIdxs,
		MessageInfos:      file_refund_v1_gateway_proto_msgTypes,
	}.Build()
	File_refund_v1_gateway_proto = out.File
	file_refund_v1_gateway_proto_goTypes = nil
	file_refund_v1_gateway_proto_depIdxs = nil
}
