// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: backoffice/refund/v1/refund.proto

package refundbackofficev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *structpb.Struct       `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_backoffice_refund_v1_refund_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backoffice_refund_v1_refund_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_backoffice_refund_v1_refund_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetQuery() *structpb.Struct {
	if x != nil {
		return x.Query
	}
	return nil
}

type SetBankEnabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBankEnabledRequest) Reset() {
	*x = SetBankEnabledRequest{}
	mi := &file_backoffice_refund_v1_refund_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBankEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBankEnabledRequest) ProtoMessage() {}

func (x *SetBankEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backoffice_refund_v1_refund_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBankEnabledRequest.ProtoReflect.Descriptor instead.
func (*SetBankEnabledRequest) Descriptor() ([]byte, []int) {
	return file_backoffice_refund_v1_refund_proto_rawDescGZIP(), []int{1}
}

func (x *SetBankEnabledRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetBankEnabledRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type JsonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Value        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonResponse) Reset() {
	*x = JsonResponse{}
	mi := &file_backoffice_refund_v1_refund_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonResponse) ProtoMessage() {}

func (x *JsonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backoffice_refund_v1_refund_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonResponse.ProtoReflect.Descriptor instead.
func (*JsonResponse) Descriptor() ([]byte, []int) {
	return file_backoffice_refund_v1_refund_proto_rawDescGZIP(), []int{2}
}

func (x *JsonResponse) GetData() *structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_backoffice_refund_v1_refund_proto protoreflect.FileDescriptor

const file_backoffice_refund_v1_refund_proto_rawDesc = "" +
	"\n" +
	"!backoffice/refund/v1/refund.proto\x12\x1ebridgepay.refund.backoffice.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"<\n" +
	"\vListRequest\x12-\n" +
	"\x05query\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05query\"A\n" +
	"\x15SetBankEnabledRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\":\n" +
	"\fJsonResponse\x12*\n" +
	"\x04data\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x04data2\xb5\x03\n" +
	"\x17BackofficeRefundService\x12h\n" +
	"\vListRefunds\x12+.bridgepay.refund.backoffice.v1.ListRequest\x1a,.bridgepay.refund.backoffice.v1.JsonResponse\x12f\n" +
	"\tListBanks\x12+.bridgepay.refund.backoffice.v1.ListRequest\x1a,.bridgepay.refund.backoffice.v1.JsonResponse\x12u\n" +
	"\x0eSetBankEnabled\x125.bridgepay.refund.backoffice.v1.SetBankEnabledRequest\x1a,.bridgepay.refund.backoffice.v1.JsonResponse\x12Q\n" +
	"\tSyncBanks\x12\x16.google.protobuf.Empty\x1a,.bridgepay.refund.backoffice.v1.JsonResponseBEZCbridgepay-payment-contracts/backoffice/refund/v1;refundbackofficev1b\x06proto3"

var (
	file_backoffice_refund_v1_refund_proto_rawDescOnce sync.Once
	file_backoffice_refund_v1_refund_proto_rawDescData []byte
)

func file_backoffice_refund_v1_refund_proto_rawDescGZIP() []byte {
	file_backoffice_refund_v1_refund_proto_rawDescOnce.Do(func() {
		file_backoffice_refund_v1_refund_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backoffice_refund_v1_refund_proto_rawDesc), len(file_backoffice_refund_v1_refund_proto_rawDesc)))
	})
	return file_backoffice_refund_v1_refund_proto_rawDescData
}

var file_backoffice_refund_v1_refund_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_backoffice_refund_v1_refund_proto_goTypes = []any{
	(*ListRequest)(nil),           // 0: bridgepay.refund.backoffice.v1.ListRequest
	(*SetBankEnabledRequest)(nil), // 1: bridgepay.refund.backoffice.v1.SetBankEnabledRequest
	(*JsonResponse)(nil),          // 2: bridgepay.refund.backoffice.v1.JsonResponse
	(*structpb.Struct)(nil),       // 3: google.protobuf.Struct
	(*structpb.Value)(nil),        // 4: google.protobuf.Value
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_backoffice_refund_v1_refund_proto_depIdxs = []int32{
	3, // 0: bridgepay.refund.backoffice.v1.ListRequest.query:type_name -> google.protobuf.Struct
	4, // 1: bridgepay.refund.backoffice.v1.JsonResponse.data:type_name -> google.protobuf.Value
	0, // 2: bridgepay.refund.backoffice.v1.BackofficeRefundService.ListRefunds:input_type -> bridgepay.refund.backoffice.v1.ListRequest
	0, // 3: bridgepay.refund.backoffice.v1.BackofficeRefundService.ListBanks:input_type -> bridgepay.refund.backoffice.v1.ListRequest
	1, // 4: bridgepay.refund.backoffice.v1.BackofficeRefundService.SetBankEnabled:input_type -> bridgepay.refund.backoffice.v1.SetBankEnabledRequest
	5, // 5: bridgepay.refund.backoffice.v1.BackofficeRefundService.SyncBanks:input_type -> google.protobuf.Empty
	2, // 6: bridgepay.refund.backoffice.v1.BackofficeRefundService.ListRefunds:output_type -> bridgepay.refund.backoffice.v1.JsonResponse
	2, // 7: bridgepay.refund.backoffice.v1.BackofficeRefundService.ListBanks:output_type -> bridgepay.refund.backoffice.v1.JsonResponse
	2, // 8: bridgepay.refund.backoffice.v1.BackofficeRefundService.SetBankEnabled:output_type -> bridgepay.refund.backoffice.v1.JsonResponse
	2, // 9: bridgepay.refund.backoffice.v1.BackofficeRefundService.SyncBanks:output_type -> bridgepay.refund.backoffice.v1.JsonResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_backoffice_refund_v1_refund_proto_init() }
func file_backoffice_refund_v1_refund_proto_init() {
	if File_backoffice_refund_v1_refund_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backoffice_refund_v1_refund_proto_rawDesc), len(file_backoffice_refund_v1_refund_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backoffice_refund_v1_refund_proto_goTypes,
		DependencyIndexes: file_backoffice_refund_v1_refund_proto_depIdxs,
		MessageInfos:      file_backoffice_refund_v1_refund_proto_msgTypes,
	}.Build()
	File_backoffice_refund_v1_refund_proto = out.File
	file_backoffice_refund_v1_refund_proto_goTypes = nil
	file_backoffice_refund_v1_refund_proto_depIdxs = nil
}
