// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: backoffice/refund/v1/refund.proto

package refundbackofficev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackofficeRefundService_ListRefunds_FullMethodName    = "/bridgepay.refund.backoffice.v1.BackofficeRefundService/ListRefunds"
	BackofficeRefundService_ListBanks_FullMethodName      = "/bridgepay.refund.backoffice.v1.BackofficeRefundService/ListBanks"
	BackofficeRefundService_SetBankEnabled_FullMethodName = "/bridgepay.refund.backoffice.v1.BackofficeRefundService/SetBankEnabled"
	BackofficeRefundService_SyncBanks_FullMethodName      = "/bridgepay.refund.backoffice.v1.BackofficeRefundService/SyncBanks"
)

// BackofficeRefundServiceClient is the client API for BackofficeRefundService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Calls require both the backoffice mTLS identity and a valid Core-issued user
// JWT in gRPC metadata as `authorization: Bearer <token>`.
type BackofficeRefundServiceClient interface {
	ListRefunds(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	ListBanks(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	SetBankEnabled(ctx context.Context, in *SetBankEnabledRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	SyncBanks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*JsonResponse, error)
}

type backofficeRefundServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackofficeRefundServiceClient(cc grpc.ClientConnInterface) BackofficeRefundServiceClient {
	return &backofficeRefundServiceClient{cc}
}

func (c *backofficeRefundServiceClient) ListRefunds(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, BackofficeRefundService_ListRefunds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backofficeRefundServiceClient) ListBanks(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, BackofficeRefundService_ListBanks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backofficeRefundServiceClient) SetBankEnabled(ctx context.Context, in *SetBankEnabledRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, BackofficeRefundService_SetBankEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backofficeRefundServiceClient) SyncBanks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, BackofficeRefundService_SyncBanks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackofficeRefundServiceServer is the server API for BackofficeRefundService service.
// All implementations must embed UnimplementedBackofficeRefundServiceServer
// for forward compatibility.
//
// Calls require both the backoffice mTLS identity and a valid Core-issued user
// JWT in gRPC metadata as `authorization: Bearer <token>`.
type BackofficeRefundServiceServer interface {
	ListRefunds(context.Context, *ListRequest) (*JsonResponse, error)
	ListBanks(context.Context, *ListRequest) (*JsonResponse, error)
	SetBankEnabled(context.Context, *SetBankEnabledRequest) (*JsonResponse, error)
	SyncBanks(context.Context, *emptypb.Empty) (*JsonResponse, error)
	mustEmbedUnimplementedBackofficeRefundServiceServer()
}

// UnimplementedBackofficeRefundServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackofficeRefundServiceServer struct{}

func (UnimplementedBackofficeRefundServiceServer) ListRefunds(context.Context, *ListRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRefunds not implemented")
}
func (UnimplementedBackofficeRefundServiceServer) ListBanks(context.Context, *ListRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBanks not implemented")
}
func (UnimplementedBackofficeRefundServiceServer) SetBankEnabled(context.Context, *SetBankEnabledRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBankEnabled not implemented")
}
func (UnimplementedBackofficeRefundServiceServer) SyncBanks(context.Context, *emptypb.Empty) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncBanks not implemented")
}
func (UnimplementedBackofficeRefundServiceServer) mustEmbedUnimplementedBackofficeRefundServiceServer() {
}
func (UnimplementedBackofficeRefundServiceServer) testEmbeddedByValue() {}

// UnsafeBackofficeRefundServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackofficeRefundServiceServer will
// result in compilation errors.
type UnsafeBackofficeRefundServiceServer interface {
	mustEmbedUnimplementedBackofficeRefundServiceServer()
}

func RegisterBackofficeRefundServiceServer(s grpc.ServiceRegistrar, srv BackofficeRefundServiceServer) {
	// If the following call panics, it indicates UnimplementedBackofficeRefundServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackofficeRefundService_ServiceDesc, srv)
}

func _BackofficeRefundService_ListRefunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackofficeRefundServiceServer).ListRefunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackofficeRefundService_ListRefunds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackofficeRefundServiceServer).ListRefunds(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackofficeRefundService_ListBanks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackofficeRefundServiceServer).ListBanks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackofficeRefundService_ListBanks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackofficeRefundServiceServer).ListBanks(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackofficeRefundService_SetBankEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBankEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackofficeRefundServiceServer).SetBankEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackofficeRefundService_SetBankEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackofficeRefundServiceServer).SetBankEnabled(ctx, req.(*SetBankEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackofficeRefundService_SyncBanks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackofficeRefundServiceServer).SyncBanks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackofficeRefundService_SyncBanks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackofficeRefundServiceServer).SyncBanks(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// BackofficeRefundService_ServiceDesc is the grpc.ServiceDesc for BackofficeRefundService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackofficeRefundService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridgepay.refund.backoffice.v1.BackofficeRefundService",
	HandlerType: (*BackofficeRefundServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRefunds",
			Handler:    _BackofficeRefundService_ListRefunds_Handler,
		},
		{
			MethodName: "ListBanks",
			Handler:    _BackofficeRefundService_ListBanks_Handler,
		},
		{
			MethodName: "SetBankEnabled",
			Handler:    _BackofficeRefundService_SetBankEnabled_Handler,
		},
		{
			MethodName: "SyncBanks",
			Handler:    _BackofficeRefundService_SyncBanks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backoffice/refund/v1/refund.proto",
}
